spring:
  datasource:
    url: jdbc:mysql://192.168.3.59:3306/ykh?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Admin@123
    driver-class-name: com.mysql.jdbc.Driver

